# Sample Userplex configuration file

person:
  person_client_id: "client_id"
  person_client_secret: "client_secret"
  person_base_url: "https://person_url.com"
  person_auth0_url: "https://auth0.com"

notifications:
    email:
        # your smtp relay may require authentication (AWS SES does), so make
        # sure to set the parameters below to an authorized sender
        host: "email-smtp.us-east-1.amazonaws.com"
        port: 587
        from: "myauthorizedsender@example.net"
        cc:   "bob.kelso@gmail.com"
        replyto: "Something <something@example.com>"
        auth:
            user: "AKIAI3TZL"
            pass: "AoXAy......"

# A UID map translates a ldapuid into a localuid
mycustomawsuidmap1: &CUSTOMMAP1
  - ldap_username: bkelso
    local_username: bob

  - ldap_username: tanderson
    local_username: neo

# signinurl: "https://myawsaccount.signin.aws.amazon.com/console"
aws:
  - account_name: "myawsaccount"
    notify_new_users: true
    credentials:
        # if blank, will use the default aws credential flow
        accesskey: AKIAnnnn
        secretkey: YOLOMAN
    group_mapping:
      - ldap_group: "sysadmins"
        iam_groups:
          - ldapmanaged
          - admin
      - ldap_group: "developers"
        iam_groups:
          - ldapmanaged
          - dev_only
      - default: true
        iam_groups:
          - ldapmanaged

authorized_keys:
    - name: all_authorizedkeys
      # anchor to the uid map defined above
      username_map: *CUSTOMMAP1
      ldapgroups:
        - sysadmins
        - developers
        - devssh
      # {username} will be replaced with the primary username for the user being created
      path: /data/puppet/modules/users/files/{username}/.ssh/authorized_keys
      # {env:ROOT_DIR} will be replaced with the env var $ROOT_DIR
      # path: /data/puppet/modules/users/files/{env:ROOT_DIR}/.ssh/authorized_keys

    - name: root_authorizedkeys
      ldapgroups:
        - sysadmins
      username_map: *CUSTOMMAP1
      path: /data/puppet/modules/users/files/root/.ssh/authorized_keys
